//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int MaterialsId { get; set; }
        public string MaterialName { get; set; }
        public Nullable<double> CountOfMaterial { get; set; }
    }
}
