//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LopushokApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsHistory
    {
        public int ID { get; set; }
        public Nullable<int> OldMinPrice { get; set; }
        public Nullable<int> NewMinPrice { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
